# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 626)
        self.mainTab = QtWidgets.QWidget(MainWindow)
        self.mainTab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainTab.setObjectName("mainTab")
        self.colon = QtWidgets.QTabWidget(self.mainTab)
        self.colon.setGeometry(QtCore.QRect(0, 0, 992, 471))
        self.colon.setObjectName("colon")
        self.Colon = QtWidgets.QWidget()
        self.Colon.setObjectName("Colon")
        self.colonSingleImage = QtWidgets.QLabel(self.Colon)
        self.colonSingleImage.setGeometry(QtCore.QRect(10, 100, 300, 300))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(11)
        self.colonSingleImage.setFont(font)
        self.colonSingleImage.setFrameShape(QtWidgets.QFrame.Box)
        self.colonSingleImage.setAlignment(QtCore.Qt.AlignCenter)
        self.colonSingleImage.setObjectName("colonSingleImage")
        self.colonSingleOpenImage = QtWidgets.QPushButton(self.Colon)
        self.colonSingleOpenImage.setGeometry(QtCore.QRect(320, 100, 75, 23))
        self.colonSingleOpenImage.setObjectName("colonSingleOpenImage")
        self.colonSinglePredict = QtWidgets.QLabel(self.Colon)
        self.colonSinglePredict.setGeometry(QtCore.QRect(10, 410, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.colonSinglePredict.setFont(font)
        self.colonSinglePredict.setObjectName("colonSinglePredict")
        self.colonSinglePredict_text = QtWidgets.QLabel(self.Colon)
        self.colonSinglePredict_text.setGeometry(QtCore.QRect(80, 410, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.colonSinglePredict_text.setFont(font)
        self.colonSinglePredict_text.setObjectName("colonSinglePredict_text")
        self.colonBatchOpenDir = QtWidgets.QPushButton(self.Colon)
        self.colonBatchOpenDir.setGeometry(QtCore.QRect(860, 100, 75, 23))
        self.colonBatchOpenDir.setObjectName("colonBatchOpenDir")
        self.colonBatchPredict = QtWidgets.QTextEdit(self.Colon)
        self.colonBatchPredict.setGeometry(QtCore.QRect(410, 100, 441, 321))
        self.colonBatchPredict.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.colonBatchPredict.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.colonBatchPredict.setObjectName("colonBatchPredict")
        self.line = QtWidgets.QFrame(self.Colon)
        self.line.setGeometry(QtCore.QRect(390, 50, 20, 371))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.colonSingle = QtWidgets.QLabel(self.Colon)
        self.colonSingle.setGeometry(QtCore.QRect(10, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.colonSingle.setFont(font)
        self.colonSingle.setObjectName("colonSingle")
        self.colonBatch = QtWidgets.QLabel(self.Colon)
        self.colonBatch.setGeometry(QtCore.QRect(420, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.colonBatch.setFont(font)
        self.colonBatch.setObjectName("colonBatch")
        self.colonSingleBeginPredict = QtWidgets.QPushButton(self.Colon)
        self.colonSingleBeginPredict.setGeometry(QtCore.QRect(320, 140, 75, 23))
        self.colonSingleBeginPredict.setObjectName("colonSingleBeginPredict")
        self.colonBatchBeginPredict = QtWidgets.QPushButton(self.Colon)
        self.colonBatchBeginPredict.setGeometry(QtCore.QRect(860, 140, 75, 23))
        self.colonBatchBeginPredict.setObjectName("colonBatchBeginPredict")
        self.colonBatchSaveCSV = QtWidgets.QPushButton(self.Colon)
        self.colonBatchSaveCSV.setGeometry(QtCore.QRect(860, 180, 75, 23))
        self.colonBatchSaveCSV.setObjectName("colonBatchSaveCSV")
        self.colonLoadModel = QtWidgets.QPushButton(self.Colon)
        self.colonLoadModel.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.colonLoadModel.setObjectName("colonLoadModel")
        self.colonBatchClear = QtWidgets.QPushButton(self.Colon)
        self.colonBatchClear.setGeometry(QtCore.QRect(860, 220, 75, 23))
        self.colonBatchClear.setObjectName("colonBatchClear")
        self.colon.addTab(self.Colon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.colon.addTab(self.tab_2, "")
        self.message = QtWidgets.QTextEdit(self.mainTab)
        self.message.setGeometry(QtCore.QRect(10, 480, 941, 101))
        self.message.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.message.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.message.setObjectName("message")
        MainWindow.setCentralWidget(self.mainTab)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.colon.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.colonSingleImage.setText(_translate("MainWindow", "无"))
        self.colonSingleOpenImage.setText(_translate("MainWindow", "打开图片"))
        self.colonSinglePredict.setText(_translate("MainWindow", "识别结果:"))
        self.colonSinglePredict_text.setText(_translate("MainWindow", "无"))
        self.colonBatchOpenDir.setText(_translate("MainWindow", "打开文件夹"))
        self.colonSingle.setText(_translate("MainWindow", "单张识别"))
        self.colonBatch.setText(_translate("MainWindow", "批量识别"))
        self.colonSingleBeginPredict.setText(_translate("MainWindow", "开始识别"))
        self.colonBatchBeginPredict.setText(_translate("MainWindow", "开始识别"))
        self.colonBatchSaveCSV.setText(_translate("MainWindow", "导出CSV文件"))
        self.colonLoadModel.setText(_translate("MainWindow", "载入预训练模型"))
        self.colonBatchClear.setText(_translate("MainWindow", "清  除"))
        self.colon.setTabText(self.colon.indexOf(self.Colon), _translate("MainWindow", "结肠癌预测"))
        self.colon.setTabText(self.colon.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
